### ISSUE TITLE
音的收尾戛然而止

### ISSUE THREAD

**Issue by 3c** [AutoPiano/AutoPiano#1]
按一个音，结尾的时候突然停止，感觉很违和。
可否延长播放时间，或者在有限时间内渐进完毕

**Comment by 3c** [comment]
另外长按一个音，会不停的重复播放，中间有停顿。正常应该就是一个长音

**Comment by WarpPrism** [comment]
目前单个音符的持续时长是 一个标准 4分音符，近期会考虑优化，加上延音

**Comment by MountainC44** [comment]
挺好玩的，加上延音的话效果感觉会更好，那种戛然而止的感觉不爽，哈哈

**Comment by code2038** [comment]
体验的时候,戴耳机听d键的音量偏低,与其它键区别明显,不知是不是我个人设备的问题.

**Comment by WarpPrism** [comment]
> 体验的时候,戴耳机听d键的音量偏低,与其它键区别明显,不知是不是我个人设备的问题.

d键的声音是正常的，但黑键d 音量偏低。钢琴的黑键一般比白键音量低一点，很正常

**Comment by KagurazakaHanabi** [comment]
延音踏板？（逃
