### ISSUE TITLE
Project: 已知Bug列表

### ISSUE THREAD

**Issue by WarpPrism** [AutoPiano/AutoPiano#82]
- [x] 音量设置为0时，声音不正常
- [x] Firefox 壁纸滚动时会闪烁
- [x] 音符雨组件可能会导致浏览器崩溃
- [x] 乐谱播放时，音量无法调节
- [x] 创作乐谱时，滚动位置不正确
- [x] 语言切换时，部分js代码设置的语言没切换，lazyload?

**Comment by huasheng-yue** [comment]
1）按键-出声的延时问题
2）抬起按键后，会又跟着出现一次按键响动
3）不能自定义音程与按键的对应关系
4）没有力度感应声效
