### ISSUE TITLE
小白再次求问一下

### ISSUE THREAD

**Issue by qffsy** [AutoPiano/AutoPiano#85]
本地点击index.html 文件 打开是白屏是怎么回事呀，上次到服务器打开也是白屏，有没有兄der 指点一二
需要修改哪里码

**Comment by WarpPrism** [comment]
将autopiano_build_demo 下的文件放到静态服务器下，然后通过url访问

**Comment by qffsy** [comment]
已经设置成纯静态啦  还是打开一片空白

**Comment by WarpPrism** [comment]
那就需要检查你的nginx配置，Url路径是否正确了，也可以F12打开控制台，看html、js、css文件是否都拿到。
如果都没问题，建议Google找下方案

**Comment by qffsy** [comment]
大锅 嘿嘿嘿 

[http://y.hiooi.cn/](url)

**Comment by qffsy** [comment]
5个软妹币 可行

**Comment by WarpPrism** [comment]
你的index.html文件不对，要用autopiano_build_demo下的index.html

**Comment by qffsy** [comment]
解决啦  谢谢谢谢谢谢谢谢谢谢谢谢
 软妹币怎么查收 来个地址
