### ISSUE TITLE
Project: 增加数字小键盘按键支持

### ISSUE THREAD

**Issue by WarpPrism** [AutoPiano/AutoPiano#92]
- 需求描述：数字小键盘的健位补充。实现多套不同键位的映射。
- 优先级：**高**

**Comment by huasheng-yue** [comment]
非常敬佩作者的努力！赞一个！加星！真的非常期待：用电脑键盘取代MIDI键盘！
1）力度响应声效的表现，可能需要keystone那样的键盘？或者改为触摸控制屏幕版本，通过触控点面积大小及移动表现音效的变化？
2）界面布局可以借鉴freepiano，允许自定义按键或者触控响应
